### ISSUE TITLE
Not correct requirements.txt

### ISSUE THREAD

**Issue by Cyero** [pythontoday/schedule_python#1]
Файл содержит многие пакеты, не относящиеся к проекту. Для полного функционирования достаточно лишь следующих пакетов : 
- requests==2.27.1
- schedule==1.1.0

P.S: для корректной генерации requirements.txt можете использовать "pipreqs" или же перейти на более современные пакетные менеджеры, например, "poetry"

**Comment by pythontoday** [comment]
Thanks! Fixed.
